# Generated by Django 5.2.13 on 2026-04-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('subject', models.CharField(choices=[('physics', 'Physics'), ('chemistry', 'Chemistry'), ('mathematics', 'Mathematics'), ('biology', 'Biology'), ('english', 'English')], default='physics', max_length=20)),
                ('class_level', models.CharField(choices=[('10', 'Class 10'), ('12', 'Class 12')], default='12', max_length=5)),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/%Y/%m/')),
                ('file_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'materials',
                'ordering': ['-created_at'],
            },
        ),
    ]
